### ISSUE TITLE
test) ft_export

### ISSUE THREAD

**Issue by habvi** [habvi/42_minishell#159]

**Comment by ak0327** [comment]
* tokenize, parse, expansion終わったらテスト作れそう
* `sed 's/\\//g'` で`\`消して評価できれば...と思ったが、minishellが`'`をまだ解釈できないので`sed`や`tr`が使えなかった

---
そもそもminishellがバックスラッシュ解釈しないのでsed, tr使えない気がしてきた
", 'で頑張ればいけるのか...??
少なくとも一般的な記法ではなくなりそう

**Comment by habvi** [comment]
#225 。閉じ。
