### ISSUE TITLE
fix: exit 1 && echo a

### ISSUE THREAD

**Issue by habvi** [habvi/42_minishell#236]
- [ ] `exit 1 && echo a` : not print  exit -> print exit
`./minishell` では stderr に出てるのに、python test だと stderr に出てないことになって落ちてる…

**Comment by ak0327** [comment]
subprocessで立ち上げたminishellとbashの`interactive`に差異があることが原因みたいですね。
非pipeで実行したexitの`exit`出力に差異が生じるはずです。
exitのテストは手動になりますねーという話をし、run_exit.py の合わないケースをコメントアウトにした記憶があります。

あと普通にis_interactiveのハンドリングをミスっていたので修正しました。mix_testで、ですが... 1d0342b
`exec_command_each()`を通ると以降は`context->is_interactive = false;`になる

**Comment by habvi** [comment]
そんな話…確実にしましたね🥹
#231 での修正ありがとうございます！
閉じー。
