### ISSUE TITLE
github test

### ISSUE THREAD

**Issue by habvi** [habvi/42_minishell#3]
- 右下 Development -> Create a branch で Issue に紐づいた branch ができる
  remote の branch を local に反映
  ```shell
  git fetch
  git checkout 3-github-test
  ```
  この branch に push するとこの Issue の下に並ぶ

**Comment by ak0327** [comment]
ローカルでブランチ作成後、右下Development -> Branch選択 -> Apply でも可能ですー！
```shell
# new_branch作成元のbranchに移動（大体main?)
git checkout <branch_name>

# branchを作成
git checkout -b <new_branch_name>

# リモートに登録
git branch -u origin <new_branch_name>
```

https://qiita.com/TetsuTaka/items/5ab227a8bd2cd7106833

**Comment by ak0327** [comment]
>   この branch に push するとこの Issue の下に並ぶ

`git commit -m "#<branch_no> message"`
で並ぶかもです

**Comment by habvi** [comment]
それしてやっと 1 個並びました！毎回は忘れそう…

**Comment by ak0327** [comment]
直前のcommit messageであれば
```
git commit --amend -m "update message"
git push -f
```
で変更できますが、大量にあると面倒かもです...

https://www.granfairs.com/blog/staff/git-commit-fix

**Comment by habvi** [comment]
ですね…直前でない場合は `rebase` になりそうです
癖つけます…
(SNS のように使ってますが良いのか…？)

**Comment by ak0327** [comment]
🥺

**Comment by habvi** [comment]
毎回 commit に #Issue番号 よりは PR 出すと自動でここに link されるっぽい
PR の方には commit が並んでる
https://developer.mamezou-tech.com/blogs/2022/03/28/github-create-branch-from-issue/

**Comment by ak0327** [comment]
`git pull`で`4-github-test`branchの中身が反映されていることが確認できましたー
pull requestの流れがなんとなく分かった気がする

**Comment by habvi** [comment]
`git fetch --prune` で削除された remote の branch を local と比較して local から消してくれました
https://tracpath.com/docs/git-fetch/
