### ISSUE TITLE
#4 github test2

### ISSUE THREAD

**Issue by ak0327** [habvi/42_minishell#4]
#3 へのプルリク練習用

**Comment by habvi** [comment]
close されてるのに対して commit してしまったので reopen してみる。
今度は review をお願いしてみたい
PR が自動で出てこない…
あ、それ用の branch を切らないといけない…？

**Comment by habvi** [comment]
reopen せずに素直に新しい branch が良さそう

**Comment by ak0327** [comment]
↑でPRした時は、[PR page](https://github.com/habvi/42_minishell/pulls)からnew PRで作成しました

**Comment by habvi** [comment]
それではもう１回 reopen

**Comment by habvi** [comment]
#6 これにて done

**Comment by habvi** [comment]
と、思ったらここにさっきの PR が紐づいてない
上の紫の Merged が欲しい

**Comment by habvi** [comment]
PR の方から mention すれば出ました。これはほしいですねー

**Comment by habvi** [comment]
4-github-test branch の役目が終わってたので削除してみました
